<?php

namespace ContainerQTPy22v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RgCiuhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._rgCiuh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._rgCiuh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine_question' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'doctrine_reponse' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
        ], [
            'doctrine_question' => 'App\\Repository\\QuestionRepository',
            'doctrine_reponse' => 'App\\Repository\\ReponseRepository',
        ]);
    }
}
