<?php

namespace ContainerKmWZYXL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CH2SAnNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CH2SAnN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CH2SAnN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'anwsers' => ['privates', 'App\\Repository\\AnswerRepository', 'getAnswerRepositoryService', true],
            'categorie' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'anwsers' => 'App\\Repository\\AnswerRepository',
            'categorie' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
