<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTPy22v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTPy22v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQTPy22v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQTPy22v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQTPy22v\App_KernelDevDebugContainer([
    'container.build_hash' => 'QTPy22v',
    'container.build_id' => 'd2eb3961',
    'container.build_time' => 1664457335,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTPy22v');
